name: SQL File Change Notification

on:
  pull_request:
    types: [closed]

jobs:
  notify:
    if: github.event.pull_request.merged == true  # Only run if the PR is merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR commits
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Fetch only the latest commit

      - name: Fetch base and head commits
        run: |
          git fetch origin ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} --depth=1

      - name: Detect .sql files in PR
        id: detect_files
        run: |
          FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '\.sql$' || true)
          FILES=$(echo "$FILES" | tr '\n' ' ') # Remove newlines and join the file paths with spaces
          echo "Detected SQL files: $FILES"  # This prints to the console for debugging
          echo "FILES=$FILES" >> $GITHUB_ENV

      - name: Send Slack Notification
        if: ${{ env.FILES != '' }}  # Check if FILES is not empty
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"A PR containing .sql files has been merged: ${{ github.event.pull_request.html_url }}"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
