name: SQL File Notification

on:
  pull_request:
    types: [closed]  # Trigger when a PR is closed

jobs:
  notify:
    if: github.event.pull_request.merged == true  # Only run if the PR is merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the full history, including all branches

      - name: Detect .sql files in PR
        id: detect_files
        run: |
          FILES=$(git diff --name-only 6acc792ec3d00361d4b2b002f281ce5facf926c4 46b1ec65d28b352d9c00b23fd61e45c1562626d4 | grep '\.sql$' || true)
          FILES=$(echo "$FILES" | tr '\n' ' ') # Replace newlines with spaces
          echo "files=$FILES" >> $GITHUB_ENV

      - name: Send Slack Notification
        run: |
          echo ${{ secrets.SLACK_WEBHOOK_URL }}
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"A PR containing .sql files has been merged: ${{ github.event.pull_request.html_url }}"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
