name: SQL File Change Notification

on:
  pull_request:
    types: [closed]

jobs:
  notify:
    if: github.event.pull_request.merged == true  # Only run if the PR is merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch the last two commits

      - name: Detect .sql files in the last commit
        id: detect_files
        run: |
          # Get the latest commit
          LATEST_COMMIT=$(git rev-parse HEAD)
          # Get the parent commit of the latest commit
          PREVIOUS_COMMIT=$(git rev-parse HEAD^)
          
          echo "Latest Commit: $LATEST_COMMIT"
          echo "Previous Commit: $PREVIOUS_COMMIT"
          
          # Compare the two commits for .sql files
          FILES=$(git diff --name-only HEAD^1 HEAD | grep '\.sql$' || true)
          FILES=$(echo "$FILES" | tr '\n' ' ' | xargs) # Remove newlines and trim spaces
          echo "Detected SQL files: $FILES"
          echo "FILES=$FILES" >> $GITHUB_ENV

      - name: Send Slack Notification
        if: ${{ env.FILES && env.FILES != '' }}  # Ensure FILES is non-empty
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"A PR containing .sql files has been merged: ${{ github.event.pull_request.html_url }}"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
